config/routes.rb
Rails.application.routes.draw do
  
  root 'tax_payers#index'
  resources :tax_payers
  resources :tax_payers do
    get 'request_otp' => 'tax_payers#request_otp', as: :request_otp
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tax_payer.rb
class TaxPayer < ApplicationRecord
  include HTTParty
  debug_output $stdout  
  base_uri "http://devapi.gstsystem.co.in/taxpayerapi/v0.2"

  def generate_encoded_aes_256_bit_key

    cipher = OpenSSL::Cipher.new('aes-256-ecb')
    cipher.encrypt
    key = cipher.random_key
    #iv = cipher.random_iv #Not required for ECB

    Base64.encode64(key)
  end

  def extract_public_key_from_certificate

    certificate_file_content = File.read("#{Rails.root}/lib/certificates/GSTN_G2B_SANDBOX_UAT_public.cer")
    #cert = OpenSSL::X509::Certificate.new(Base64.decode64(certificate_file_content)) <- Big Error
    # The error I was facing was decoding the certificate file
    cert = OpenSSL::X509::Certificate.new(certificate_file_content)
    cert.public_key

  end


  def read_from_rsa_file
    rsa_file = "-----BEGIN RSA PUBLIC KEY-----\n"+"MIIBCgKCAQEAn4ccEVpmsRfrUvxK6yfkg6brTJoGe90qzDNWOSqXJh51mwyL\n"+"Kjd7mccSaL7oMKTkXKLRmZvZtR1NYWnAU6nuKNjDQOC6LTzhoSE7siL2rneh\n"+"0+A9rXyjEl6FuYp+ilV5rrsuWR3RLCUDYOFkIobHDdhbl/B8Ol05bLrZvU1X\n"+"In7E98j47q/rWGp+SiHA5Ui7hAw+b2UCv8os8HWKmr6zNDziKPCGabrZTws/\n"+"e1XJ0/uW5mxTfX/DOjbukP+aosMrlD1kVocJr+SrVRKzIOiC7FYuY6q2CGY5\n"+"+soXz8cQi7be6h5wJvZB9HdU6mYzTk4yw/bnNvuqlGIgoGF0nZznMwIDAQAB\n"+"-----END RSA PUBLIC KEY-----\n"
    rsa = OpenSSL::PKey::RSA.new(rsa_file)
    logger.debug "***************************** RSA File Contents = #{rsa}"

    rsa

  end

  def new_rsa_key
    rsa_key = OpenSSL::PKey::RSA.new(2048)
    public_key = rsa_key.public_key

    logger.debug "111111 Sample RSA data = #{public_key}"

    public_key

  end

  def convert_public_key_to_old_ruby_pkcs1_format

    gst_pem_file = File.read("#{Rails.root}/lib/certificates/GSTN_G2B_SANDBOX_UAT_public.pem")

    logger.debug "***************************** PEM File Contents = #{gst_pem_file}"

    rsa = OpenSSL::PKey::RSA.new(gst_pem_file)
    modulus = rsa.n
    exponent = rsa.e

    ary = [OpenSSL::ASN1::Integer.new(modulus), OpenSSL::ASN1::Integer.new(exponent)]
    pub_key = OpenSSL::ASN1::Sequence.new(ary)
    pem = pub_key.to_der
    base64 = Base64.encode64(pub_key.to_der)

    #This is the equivalent to the PKCS#1 encoding used before 1.9.3
    pem = "-----BEGIN RSA PUBLIC KEY-----\n#{base64}-----END RSA PUBLIC KEY-----"
    the_public_key = OpenSSL::PKey::RSA.new(pub_key)
    logger.debug "***************************** PEM File = #{pem}"

    the_public_key    

  end

  def generate_otp_request(encrypted_key)
    
    gstn_server_response = self.class.post('/authenticate', 
      :headers => {
        :clientid => 'l7xx6b008ac621824f79805cca0b205fa7fc', #Rails.application.secrets.gstn_client_id, 
        :'client-secret' => '27bef27a0d5046b4b1b1613279713cbe', #Rails.application.secrets.gstn_client_secret, 
        :'ip-usr' => '42.187.63.202', 
        :'state-cd' => '33', 
        :txn => 'OTPREQUEST',
        'Content-Type' => 'application/json'},
      :body => {
        :action => "OTPREQUEST",
        :username => self.username,
        #:app_key => encrypted_key
        :app_key => "M4AfEHQ+377Y1Zuor32nX257utICg0LPLRelyyX+ukTTvrVkb9rTO4TN7f2WbUi2rek8LoiLQkcficAsuAHtY8qAoFAOZ/UslhnYbIn4YScr1z8DpDCPbN2Dj3vTkjZqgT3Pp6fV0eoCSMOq3mg7pUNyygiNiSezP0+IT4VDTP+qKNEOB+9SIrr5QSjg8VwH2kwjPcZ0oRfJaidBI9omfdiOrVjS70iQvQXM5eZjVZ5hTGj6NNkRmJgFoDwHMgl0xom8HHFJQTlo2zl82QcoulEpfSmD4bpO51WMrJedhwrwSBXBin5zXa+CmxUeD7DNMnIkSgVY7ggAio6sfIXAgw=="
      }.to_json
    )

  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/tax_payers_controller.rb
class TaxPayersController < ApplicationController
  before_action :set_tax_payer, only: [:show, :edit, :update, :destroy]
  before_action :set_tax_payer_resource, only: [:request_otp, :submit_otp]

  # GET /tax_payers
  # GET /tax_payers.json
  def index
    @tax_payers = TaxPayer.all
  end

  # GET /tax_payers/1
  # GET /tax_payers/1.json
  def show
  end


  # GET /tax_payers/new
  def new
    @tax_payer = TaxPayer.new
  end

  # GET /tax_payers/1/edit
  def edit
  end

  # POST /tax_payers
  # POST /tax_payers.json
  def create
    @tax_payer = TaxPayer.new(tax_payer_params)

    respond_to do |format|
      if @tax_payer.save
        format.html { redirect_to @tax_payer, notice: 'Tax payer was successfully created.' }
        format.json { render :show, status: :created, location: @tax_payer }
      else
        format.html { render :new }
        format.json { render json: @tax_payer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tax_payers/1
  # PATCH/PUT /tax_payers/1.json
  def update
    respond_to do |format|
      if @tax_payer.update(tax_payer_params)
        format.html { redirect_to @tax_payer, notice: 'Tax payer was successfully updated.' }
        format.json { render :show, status: :ok, location: @tax_payer }
      else
        format.html { render :edit }
        format.json { render json: @tax_payer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tax_payers/1
  # DELETE /tax_payers/1.json
  def destroy
    @tax_payer.destroy
    respond_to do |format|
      format.html { redirect_to tax_payers_url, notice: 'Tax payer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def request_otp

    #1. Create an AES 256 bit key
    @app_key = @tax_payer.generate_encoded_aes_256_bit_key

    #2. Load the public key
    @public_key = @tax_payer.extract_public_key_from_certificate

    #3. Encrypt @app_key using Public Key
    # The error that I was continuosly facing was that I was not decoding the app_key. It must be first decoded and only then should be used
    @encrypted_key = Base64.encode64(@public_key.public_encrypt(Base64.decode64(@app_key)))

    #4. Send an OTPREQUEST to GSTN portal
    @response_text = @tax_payer.generate_otp_request(@encrypted_key).parsed_response

    respond_to do |format|
      format.html {}
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tax_payer
      @tax_payer = TaxPayer.find(params[:id])
    end

    def set_tax_payer_resource
      @tax_payer = TaxPayer.find(params[:tax_payer_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tax_payer_params
      params.require(:tax_payer).permit(:username, :gstin, :password, :app_key)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tax_payers_helper.rb
module TaxPayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gstn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='row'>
      <div class='container'>
        <div class='col-sm-8 offset-sm-2'>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tax_payers/_form.html.erb
<%= form_with(model: tax_payer, local: true) do |form| %>
  <% if tax_payer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tax_payer.errors.count, "error") %> prohibited this tax_payer from being saved:</h2>

      <ul>
      <% tax_payer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :tax_payer_username %>
  </div>

  <div class="field">
    <%= form.label :gstin %>
    <%= form.text_field :gstin, id: :tax_payer_gstin %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :tax_payer_password %>
  </div>

  <div class="field">
    <%= form.label :app_key %>
    <%= form.text_area :app_key, id: :tax_payer_app_key %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tax_payers/edit.html.erb
<h1>Editing Tax Payer</h1>

<%= render 'form', tax_payer: @tax_payer %>

<%= link_to 'Show', @tax_payer %> |
<%= link_to 'Back', tax_payers_path %>

app/views/tax_payers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tax Payers</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Username</th>
      <th>Gstin</th>
      <th>Password</th>
      <th>App key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tax_payers.each do |tax_payer| %>
      <tr>
        <td><%= link_to tax_payer.username, tax_payer %></td>        
        <td><%= tax_payer.gstin %></td>
        <td><%= tax_payer.password %></td>
        <td><%= tax_payer.app_key %></td>
        <td><%= link_to 'Edit', edit_tax_payer_path(tax_payer) %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tax Payer', new_tax_payer_path %>

app/views/tax_payers/new.html.erb
<h1>New Tax Payer</h1>

<%= render 'form', tax_payer: @tax_payer %>

<%= link_to 'Back', tax_payers_path %>

app/views/tax_payers/request_otp.html.erb
<p id="notice"><%= notice %></p>

<small><%= link_to 'Back', tax_payers_path %> </small>

<h2> Request OTP </h2>
<br>
<table class='table'>
  <tr>
    <td><strong>Username:</strong></td>
    <td><%= @tax_payer.username %></td>
    <td><strong>GSTIN:</strong></td>
    <td><%= @tax_payer.gstin %></td>
  </tr>
  <tr>
    <td><strong>Last Used App Key</strong></td>
    <td colspan='3' class='code-text'><%= @tax_payer.app_key %></td>
  </tr>
  <tr>
    <td><%= link_to 'Edit', edit_tax_payer_path(@tax_payer) %></td>
    <td><%= link_to 'Generate OTP', tax_payer_request_otp_path(@tax_payer) %></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>The AES key</td>
    <td colspan='3'><%= @app_key %></td>    
  </tr>
  <tr>
    <td>The Public Key</td>
    <td colspan='3'><%= @public_key %></td>    
  </tr>
  <tr>
    <td>Encrypted Key</td>
    <td colspan='3'><%= @encrypted_key %></td>    
  </tr>
  <tr>
    <td>Response</td>
    <td colspan='3'><%= @response_text %></td>    
  </tr>
</table>

app/views/tax_payers/show.html.erb
<p id="notice"><%= notice %></p>

<small><%= link_to 'Back', tax_payers_path %> </small>
<br>
<table class='table'>
  <tr>
    <td><strong>Username:</strong></td>
    <td><%= @tax_payer.username %></td>
    <td><strong>GSTIN:</strong></td>
    <td><%= @tax_payer.gstin %></td>
  </tr>
  <tr>
    <td><strong>Last Used App Key</strong></td>
    <td colspan='3'><%= @tax_payer.app_key %></td>
  </tr>
  <tr>
    <td><%= link_to 'Edit', edit_tax_payer_path(@tax_payer) %></td>
    <td><%= link_to 'Generate OTP', tax_payer_request_otp_path(@tax_payer) %></td>
    <td></td>
    <td></td>
  </tr>
</table>